---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: api-edx
  labels:
    name: api-edx
    solution: api-edx
    app: api-edx
spec:
  postgresVersion: 14
  instances:
    - name: api-edx
      replicas: 3
      resources:
        requests:
          cpu: 50m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: netapp-block-standard
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: api-edx
                    postgres-operator.crunchydata.com/instance-set: postgres
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 250Mi
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
      repoHost:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 1Gi
      repos:
        - name: repo1
          schedules:
            # Full backup every day at 8:00am UTC
            full: "0 8 * * *"
            # Incremental backup every 4 hours, except at 8am UTC (when the full backup is running)
            incremental: "0 0,4,12,16,20 * * *"
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
              storageClassName: netapp-file-backup
      manual:
        repoName: repo1
        options:
          - --type=full
      sidecars:
        pgbackrest:
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 250m
              memory: 500Mi
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: disable
      replicas: 2
      resources:
        requests:
          cpu: 25m
          memory: 100Mi
        limits:
          cpu: 50m
          memory: 250Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: api-edx
                    postgres-operator.crunchydata.com/role: pgbouncer
